### ISSUE TITLE
運用方針・運用理念等の明文化をして欲しい。

### ISSUE THREAD

**Issue by yanorei32** [hibit-at/avatar_network#1]
ピクシブ サービス利用規約、並びに、BOOTHガイドラインに反しているのではなかろうか。
また、アバター・アクセサリ作者等からの著作権侵害を理由とした訴訟のリスクを孕んでいると見受けられる。

### [サービス共通利用規約 | ピクシブ株式会社](https://policies.pixiv.net/#terms)

> 第14条　禁止行為
> 1. 当社もしくは第三者の著作権、意匠権等の知的財産権（第21条第1項に定義します。）、その他の権利を侵害する行為、または侵害するおそれのある行為
> 2. 本サービスおよび個別サービスに投稿等されている投稿情報を、当該著作者（創作者）の同意なくして転載する行為
> 3. 本サービスもしくは本サービスの一部（コンテンツ・情報・機能・システム・プログラム等）を使用・転用・転売・複製・送信・翻訳・翻案・改変などして、いかなる手法を問わず商業・営業目的の活動、営利を目的とした利用およびその準備を目的とした利用をすること、その他本サービスの2次利用や複製行為。但し、ユーザー本人による投稿情報は除きます。 

### [ガイドライン - BOOTH](https://booth.pm/guidelines) 内

> 禁止行為
> (中略)
> ・ クローラーなどのプログラムを使って商品を収集する行為

## 該当箇所

https://github.com/hibit-at/avatar_network/blob/400334d4c71a6278b15d316fe656a750f688ea6f/add_item_detail.py#L36-L37
https://github.com/hibit-at/avatar_network/blob/70e2e5a6eedd44615af6643858cf1e816589a1d9/add_item.py#L36-L37
https://github.com/hibit-at/avatar_network/blob/1d9ff5002c1db5390374ff90aed2ac49903a2730/add_avatar.py#L37-L38

## 取りうる対策
ソフトウェアによるアクセスの停止・並びにアバター・アクセサリ作者への個別連絡・承諾によるアイテムの手動追加に方針を変更する。

**Comment by yanorei32** [comment]
この議論は以下の2点に集約されると考えている。

- 認証なく得られるデータへのスクレイピング禁止規約の有効性
- 著作権法に定める「軽微利用」に該当するか

私は法の専門家ではない為判断しかねる。

また、遅延なくページを取得するスクリプトは、通常使用に於いて起こり得ないアクセスをするスクリプトとみなされ、電子計算機損壊等業務妨害罪に問われる可能性もあると考えている。
こちらはLibrahack事件でも言及された点である。

どの様な規約並びに法解釈で運用されているのか、運用方針・運用理念等の明文化を願いたい。

**Comment by hibit-at** [comment]
ご意見ありがとうございます。検討した結果、対応が整理ができるまで本サービスを公開停止します。

**Comment by hirokiky** [comment]
利用規約を守るのはサービス開発で難しいことですよね。

潔白で問題がまったくなさそうなサービスとは言えません。ちょっとグレーなところもありそうです。
ただ一気に諦める内容ではないと思います。

現状、私は動いているサービスを見たわけではありませんし、プログラムの解析もしていません。
サービスの性質や知れる情報から考えてみました。

## クローリングについて

BOOTHのrobots.txtを見ると、ボットによるアクセスは禁止されていないように見られます。

https://booth.pm/robots.txt

BOOTHの利用規約に禁止行為として「クローラーなどのプログラムを使って商品を収集する行為」とありますが、収集しているのがページであれば該当しないと思います。

もちろん異常な負荷をかけるのは問題ですが、常識の範囲であれば規約違反にはならなそうです。

## 著作権について

引用という形を取る可能性は十分にあると思います。
取得するページの情報を制限して、引用元を明記すれば、すぐさま著作権違反というわけではないと思います。

何よりも、アバター作者さんの権利保護や利益の保護が重要ですので、そこを侵害しないのが大切だと思います。
たとえば問い合わせを受ければページを削除するような連絡先を明記しておくなどは必要になると思います。

## 対応の方針

確認をするのであればBOOTHさんに問い合わせるのが良いかと思います。
ただ、聞かれてもOKと言いにくいかもしれません。

サービスの性質としてグレーっぽい雰囲気ではあります。
BOOTHさんとしても無思慮にOKできるものではない（お客さんを取られる可能性があるもの）ですし、著作権もどこまでが引用と扱えるかは難しいところだからです。

**Comment by hibit-at** [comment]
ご意見ありがとうございます。
本サービスの方針を以下の通り回答し、再公開します。

著作権について：
商品の作者から申立が来ない限りにおいては、使用目的（アバター及び対応商品の販売促進）及び使用規模から考えて問題ない範囲と考えております。

ガイドラインについて：
管理者から申立が来ない限りにおいては、使用目的（アバター及び対応商品の販売促進）及び使用規模から考えて問題ない範囲と考えております。

これに伴い、`info.html`を変更しました。（問い合わせ先の明記）
