### ISSUE TITLE
デバッグモードの解除

### ISSUE THREAD

**Issue by sailnov** [hibit-at/avatar_network#2]
Djangoのデバッグモードが有効になっているため、エラー発生時にデバッグ画面が表示されてしまい、データベースの接続先やユーザー名などが確認できる状態になっている。

## 該当箇所

https://github.com/hibit-at/avatar_network/blob/ef963604b25e8974e161f6752b2b3b831e011847/kaogaii2/settings.py#L84

https://github.com/hibit-at/avatar_network/blob/ef963604b25e8974e161f6752b2b3b831e011847/kaogaii2/settings.py#L95

## 取りうる対応

本番環境ではDebugモードをFalseにする。

**Comment by hibit-at** [comment]
該当 commit で修正しました。
ご指摘ありがとうございます。
（84 行目はローカル時の挙動なので問題なしです。95 行目を修正しました）
